### ISSUE TITLE
Remote desktop has invalid default route

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow-containers-desktop#61]
### Reproduce
* Create new notebook server using latest remote desktop image
* Once scheduled, click connect

### Expected
Launch remote desktop in new tab

### Actual
New tab has an invalid route (missing notebook routing info) and is not hitting the notebook server container

**Comment by Jose-Matsuda** [comment]
Asked around and found out how to test non-kubeflow-manifested images. 
Upon clicking connect (after a hard refresh if necessary) you are lead to this page: 
`https://...ca/tools/vnc/?autoconnect=true&password=vncpassword&ns=jose-matsuda`

Upon clicking connect on the current remote desktop you are lead to:
`https://....ca/notebook/jose-matsuda/reallydelete/`
Which when clicking the remote desktop are redirected to 
`https://....ca/notebook/jose-matsuda/reallydelete/tools/vnc/?auto....`

The part that caused this is probably (the only part of the nginx.conf that I changed) was https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/resources/nginx/nginx.conf#L68

I couldn't find this bug during my testing while using localhost because it _just worked_.

**Comment by Jose-Matsuda** [comment]
No need to read, just personal findings. Left is localhost and right is notebook server
![image](https://user-images.githubusercontent.com/23174198/106007890-c448ff80-6084-11eb-97b4-47c948c59c54.png)

I'm pretty sure the resolution is to add {WORKSPACE_BASE_URL}
`return 301 {WORKSPACE_BASE_URL_DECODED}/tools/vnc/?autoconnect=true&password=vncpassword;`

Did a bit of testing checking how concatenation works in nginx.conf files like
`return 301 {WORKSPACE_BASE_URL_DECODED}/ahhahah/{WORKSPACE_BASE_URL_DECODED}/hello;`
returning upon navigating to `localhost:8888` 
http://localhost:8888/workspace/ahhahah//workspace/hello
